# config.yml
features:
  - alcohol
  - malic_acid
  - flavanoids



target: 
  - target

model_params:
  multi_class: multinomial
  solver: lbfgs
  max_iter: 1000

mlflow:
  description: "Poucas as features"

